"""initial schema

Revision ID: c58385829d11
Revises: 
Create Date: 2026-07-31 01:38:38.754967

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c58385829d11'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('economic_calendar',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=60), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('timezone', sa.String(length=50), server_default='UTC', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_economic_calendar')),
    sa.UniqueConstraint('name', 'region', name='uq_economic_calendar_name_region')
    )
    op.create_index('idx_econcal_region', 'economic_calendar', ['region'], unique=False)
    op.create_table('feature_flags',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('rollout_pct', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('environment', postgresql.ENUM('development', 'staging', 'production', 'all', name='feature_flag_environment'), server_default='all', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rollout_pct BETWEEN 0 AND 100', name=op.f('ck_feature_flags_rollout_pct_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_flags')),
    sa.UniqueConstraint('key', name='uq_feature_flags_key')
    )
    op.create_index('idx_featflags_env', 'feature_flags', ['environment'], unique=False)
    op.create_index('idx_featflags_key', 'feature_flags', ['key'], unique=False)
    op.create_table('indicators',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', postgresql.ENUM('trend', 'momentum', 'volatility', 'volume', 'other', name='indicator_category'), server_default='other', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_indicators')),
    sa.UniqueConstraint('code', name='uq_indicators_code')
    )
    op.create_index('idx_indicators_category', 'indicators', ['category'], unique=False)
    op.create_index('idx_indicators_code', 'indicators', ['code'], unique=False)
    op.create_table('market_data_providers',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('provider_type', postgresql.ENUM('rest', 'websocket', 'hybrid', name='provider_type'), nullable=False),
    sa.Column('priority', sa.SmallInteger(), server_default='100', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_data_providers')),
    sa.UniqueConstraint('code', name='uq_market_data_providers_code')
    )
    op.create_index('idx_mdp_code', 'market_data_providers', ['code'], unique=False)
    op.create_index('idx_mdp_priority', 'market_data_providers', ['priority'], unique=False)
    op.create_table('markets',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('market_type', postgresql.ENUM('stocks', 'forex', 'crypto', 'commodities', 'indices', 'futures', name='market_type'), nullable=False),
    sa.Column('base_currency', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_markets')),
    sa.UniqueConstraint('code', name='uq_markets_code')
    )
    op.create_index('idx_markets_code', 'markets', ['code'], unique=False)
    op.create_index('idx_markets_type', 'markets', ['market_type'], unique=False)
    op.create_table('news',
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=600), nullable=True),
    sa.Column('sentiment', postgresql.ENUM('positive', 'neutral', 'negative', name='sentiment'), server_default='neutral', nullable=True),
    sa.Column('sentiment_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('symbols', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news')),
    sa.UniqueConstraint('url', name='uq_news_url')
    )
    op.create_index('idx_news_published', 'news', ['published_at'], unique=False)
    op.create_index('idx_news_sentiment', 'news', ['sentiment'], unique=False)
    op.create_index('idx_news_symbols', 'news', ['symbols'], unique=False, postgresql_using='gin')
    op.create_table('permissions',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('code', name='uq_permissions_code'),
    sa.UniqueConstraint('resource', 'action', name='uq_permissions_resource_action')
    )
    op.create_index('idx_permissions_code', 'permissions', ['code'], unique=False)
    op.create_index('idx_permissions_resource', 'permissions', ['resource'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name='uq_roles_name')
    )
    op.create_index('idx_roles_name', 'roles', ['name'], unique=False)
    op.create_table('symbol_categories',
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['symbol_categories.id'], name=op.f('fk_symbol_categories_parent_id_symbol_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_symbol_categories')),
    sa.UniqueConstraint('slug', name='uq_symbol_categories_slug')
    )
    op.create_index('idx_symcat_parent', 'symbol_categories', ['parent_id'], unique=False)
    op.create_index('idx_symcat_slug', 'symbol_categories', ['slug'], unique=False)
    op.create_table('system_logs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('level', postgresql.ENUM('debug', 'info', 'warning', 'error', 'critical', name='log_level'), server_default='info', nullable=False),
    sa.Column('service', sa.String(length=60), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_logs'))
    )
    op.create_index('idx_syslogs_created', 'system_logs', ['created_at'], unique=False)
    op.create_index('idx_syslogs_level', 'system_logs', ['level'], unique=False)
    op.create_index('idx_syslogs_request', 'system_logs', ['request_id'], unique=False)
    op.create_index('idx_syslogs_service', 'system_logs', ['service'], unique=False)
    op.create_table('timeframes',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('label', sa.String(length=30), nullable=False),
    sa.Column('seconds', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('seconds > 0', name=op.f('ck_timeframes_seconds_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timeframes')),
    sa.UniqueConstraint('code', name='uq_timeframes_code'),
    sa.UniqueConstraint('seconds', name='uq_timeframes_seconds')
    )
    op.create_index('idx_timeframes_code', 'timeframes', ['code'], unique=False)
    op.create_index('idx_timeframes_seconds', 'timeframes', ['seconds'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('status', postgresql.ENUM('active', 'suspended', 'pending', 'deleted', name='user_status'), server_default='pending', nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('two_factor_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('two_factor_secret', sa.String(length=255), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('locale', sa.String(length=10), server_default='en', nullable=False),
    sa.Column('timezone', sa.String(length=50), server_default='UTC', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('failed_login_count >= 0', name=op.f('ck_users_failed_login_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name='uq_users_email'),
    sa.UniqueConstraint('phone', name='uq_users_phone'),
    sa.UniqueConstraint('username', name='uq_users_username')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_status', 'users', ['status'], unique=False)
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    op.create_table('api_keys',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_prefix', sa.String(length=12), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_api_keys_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys')),
    sa.UniqueConstraint('key_hash', name='uq_api_keys_key_hash')
    )
    op.create_index('idx_api_keys_hash', 'api_keys', ['key_hash'], unique=False)
    op.create_index('idx_api_keys_prefix', 'api_keys', ['key_prefix'], unique=False)
    op.create_index('idx_api_keys_user', 'api_keys', ['user_id'], unique=False)
    op.create_table('application_settings',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('value_type', postgresql.ENUM('string', 'int', 'float', 'bool', 'json', name='setting_value_type'), server_default='json', nullable=False),
    sa.Column('scope', postgresql.ENUM('global', 'user', 'system', name='setting_scope'), server_default='global', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_application_settings_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_settings')),
    sa.UniqueConstraint('key', name='uq_application_settings_key')
    )
    op.create_index('idx_appsettings_key', 'application_settings', ['key'], unique=False)
    op.create_index('idx_appsettings_scope', 'application_settings', ['scope'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=60), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', postgresql.ENUM('success', 'failure', name='audit_status'), server_default='success', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('idx_audit_action', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_audit_created', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_request', 'audit_logs', ['request_id'], unique=False)
    op.create_index('idx_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_audit_user', 'audit_logs', ['user_id'], unique=False)
    op.create_table('economic_events',
    sa.Column('calendar_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('impact', postgresql.ENUM('low', 'medium', 'high', name='event_impact'), server_default='low', nullable=False),
    sa.Column('actual', sa.String(length=50), nullable=True),
    sa.Column('forecast', sa.String(length=50), nullable=True),
    sa.Column('previous', sa.String(length=50), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['economic_calendar.id'], name=op.f('fk_economic_events_calendar_id_economic_calendar'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_economic_events'))
    )
    op.create_index('idx_econevt_calendar', 'economic_events', ['calendar_id'], unique=False)
    op.create_index('idx_econevt_impact', 'economic_events', ['impact'], unique=False)
    op.create_index('idx_econevt_time', 'economic_events', ['event_time'], unique=False)
    op.create_table('exchanges',
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('timezone', sa.String(length=50), server_default='UTC', nullable=False),
    sa.Column('open_time', sa.String(length=8), nullable=True),
    sa.Column('close_time', sa.String(length=8), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_exchanges_market_id_markets'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exchanges')),
    sa.UniqueConstraint('code', name='uq_exchanges_code')
    )
    op.create_index('idx_exchanges_code', 'exchanges', ['code'], unique=False)
    op.create_index('idx_exchanges_market', 'exchanges', ['market_id'], unique=False)
    op.create_table('indicator_parameters',
    sa.Column('indicator_id', sa.UUID(), nullable=False),
    sa.Column('param_key', sa.String(length=60), nullable=False),
    sa.Column('default_value', sa.String(length=100), nullable=True),
    sa.Column('value_type', postgresql.ENUM('int', 'float', 'string', 'bool', name='indicator_param_value_type'), server_default='int', nullable=False),
    sa.Column('min_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('max_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], name=op.f('fk_indicator_parameters_indicator_id_indicators'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_indicator_parameters')),
    sa.UniqueConstraint('indicator_id', 'param_key', name='uq_indicator_parameters_key')
    )
    op.create_index('idx_indparam_indicator', 'indicator_parameters', ['indicator_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('category', postgresql.ENUM('alert', 'order', 'system', 'ai', 'news', 'risk', name='notification_category'), server_default='system', nullable=False),
    sa.Column('channel', postgresql.ENUM('in_app', 'email', 'push', 'sms', 'webhook', name='notification_channel'), server_default='in_app', nullable=False),
    sa.Column('priority', postgresql.ENUM('low', 'normal', 'high', 'critical', name='notification_priority'), server_default='normal', nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('idx_notif_created', 'notifications', ['created_at'], unique=False)
    op.create_index('idx_notif_user', 'notifications', ['user_id'], unique=False)
    op.create_index('idx_notif_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('portfolio',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_currency', sa.String(length=10), server_default='USD', nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=24, scale=8), server_default='0', nullable=False),
    sa.Column('equity_value', sa.Numeric(precision=24, scale=8), server_default='0', nullable=False),
    sa.Column('total_value', sa.Numeric(precision=24, scale=8), server_default='0', nullable=False),
    sa.Column('total_realized_pnl', sa.Numeric(precision=24, scale=8), server_default='0', nullable=False),
    sa.Column('total_unrealized_pnl', sa.Numeric(precision=24, scale=8), server_default='0', nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_portfolio_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio')),
    sa.UniqueConstraint('user_id', 'name', name='uq_portfolio_user_name')
    )
    op.create_index('idx_portfolio_user', 'portfolio', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_permissions')),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permissions_pair')
    )
    op.create_index('idx_role_perm_permission', 'role_permissions', ['permission_id'], unique=False)
    op.create_index('idx_role_perm_role', 'role_permissions', ['role_id'], unique=False)
    op.create_table('sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('device_label', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('expires_at > created_at', name=op.f('ck_sessions_expires_after_created')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index('idx_sessions_active', 'sessions', ['user_id', 'is_active'], unique=False)
    op.create_index('idx_sessions_expires', 'sessions', ['expires_at'], unique=False)
    op.create_index('idx_sessions_user', 'sessions', ['user_id'], unique=False)
    op.create_table('strategies',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('strategy_type', postgresql.ENUM('manual', 'automated', 'hybrid', name='strategy_type'), server_default='manual', nullable=False),
    sa.Column('status', postgresql.ENUM('draft', 'active', 'paused', 'archived', name='strategy_status'), server_default='draft', nullable=False),
    sa.Column('active_version_id', sa.UUID(), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_strategies_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategies')),
    sa.UniqueConstraint('user_id', 'name', name='uq_strategies_user_name')
    )
    op.create_index('idx_strategies_status', 'strategies', ['status'], unique=False)
    op.create_index('idx_strategies_user', 'strategies', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_user_roles_assigned_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_roles')),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_roles_pair')
    )
    op.create_index('idx_user_roles_role', 'user_roles', ['role_id'], unique=False)
    op.create_index('idx_user_roles_user', 'user_roles', ['user_id'], unique=False)
    op.create_table('watchlists',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sort_order', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_watchlists_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watchlists')),
    sa.UniqueConstraint('user_id', 'name', name='uq_watchlists_user_name')
    )
    op.create_index('idx_watchlists_user', 'watchlists', ['user_id'], unique=False)
    op.create_table('portfolio_history',
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('equity_value', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('daily_pnl', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('daily_return_pct', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], name=op.f('fk_portfolio_history_portfolio_id_portfolio'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_date', 'id', name=op.f('pk_portfolio_history')),
    sa.UniqueConstraint('portfolio_id', 'snapshot_date', name='uq_portfolio_history_date')
    )
    op.create_index('idx_portfhist_portfolio_date', 'portfolio_history', ['portfolio_id', 'snapshot_date'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rotated_from', sa.UUID(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rotated_from'], ['refresh_tokens.id'], name=op.f('fk_refresh_tokens_rotated_from_refresh_tokens'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_refresh_tokens_session_id_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name='uq_refresh_tokens_token_hash')
    )
    op.create_index('idx_refresh_expires', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index('idx_refresh_token_hash', 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index('idx_refresh_user', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('risk_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('risk_level', postgresql.ENUM('conservative', 'moderate', 'aggressive', 'custom', name='risk_level'), server_default='moderate', nullable=False),
    sa.Column('max_position_size_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('max_daily_loss_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('max_open_positions', sa.SmallInteger(), nullable=True),
    sa.Column('max_leverage', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], name=op.f('fk_risk_profiles_portfolio_id_portfolio'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_risk_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_profiles')),
    sa.UniqueConstraint('user_id', 'name', name='uq_risk_profiles_user_name')
    )
    op.create_index('idx_riskprof_portfolio', 'risk_profiles', ['portfolio_id'], unique=False)
    op.create_index('idx_riskprof_user', 'risk_profiles', ['user_id'], unique=False)
    op.create_table('strategy_versions',
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_strategy_versions_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_strategy_versions_strategy_id_strategies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategy_versions')),
    sa.UniqueConstraint('strategy_id', 'version_number', name='uq_strategy_versions_number')
    )
    op.create_index('idx_stratver_strategy', 'strategy_versions', ['strategy_id'], unique=False)
    op.create_table('symbols',
    sa.Column('exchange_id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('ticker', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('base_asset', sa.String(length=20), nullable=True),
    sa.Column('quote_asset', sa.String(length=20), nullable=True),
    sa.Column('price_precision', sa.SmallInteger(), server_default='2', nullable=False),
    sa.Column('quantity_precision', sa.SmallInteger(), server_default='2', nullable=False),
    sa.Column('min_order_size', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('tick_size', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('is_tradable', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price_precision >= 0', name=op.f('ck_symbols_price_precision_non_negative')),
    sa.ForeignKeyConstraint(['category_id'], ['symbol_categories.id'], name=op.f('fk_symbols_category_id_symbol_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], name=op.f('fk_symbols_exchange_id_exchanges'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_symbols_market_id_markets'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_symbols')),
    sa.UniqueConstraint('exchange_id', 'ticker', name='uq_symbols_exchange_ticker')
    )
    op.create_index('idx_symbols_active', 'symbols', ['is_active'], unique=False)
    op.create_index('idx_symbols_exchange', 'symbols', ['exchange_id'], unique=False)
    op.create_index('idx_symbols_market', 'symbols', ['market_id'], unique=False)
    op.create_index('idx_symbols_ticker', 'symbols', ['ticker'], unique=False)
    op.create_table('ai_analysis',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('symbol_id', sa.UUID(), nullable=True),
    sa.Column('analysis_type', postgresql.ENUM('technical', 'sentiment', 'pattern', 'portfolio', 'forecast', name='analysis_type'), nullable=False),
    sa.Column('timeframe_id', sa.UUID(), nullable=True),
    sa.Column('model_name', sa.String(length=80), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'completed', 'failed', name='analysis_status'), server_default='completed', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], name=op.f('fk_ai_analysis_symbol_id_symbols'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['timeframe_id'], ['timeframes.id'], name=op.f('fk_ai_analysis_timeframe_id_timeframes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_analysis_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_analysis'))
    )
    op.create_index('idx_aianalysis_created', 'ai_analysis', ['created_at'], unique=False)
    op.create_index('idx_aianalysis_symbol', 'ai_analysis', ['symbol_id'], unique=False)
    op.create_index('idx_aianalysis_type', 'ai_analysis', ['analysis_type'], unique=False)
    op.create_index('idx_aianalysis_user', 'ai_analysis', ['user_id'], unique=False)
    op.create_table('alerts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('symbol_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('alert_type', postgresql.ENUM('price', 'indicator', 'volume', 'news', 'custom', name='alert_type'), server_default='price', nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'paused', 'triggered', 'expired', name='alert_status'), server_default='active', nullable=False),
    sa.Column('is_recurring', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('trigger_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('trigger_count >= 0', name=op.f('ck_alerts_trigger_count_non_negative')),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], name=op.f('fk_alerts_symbol_id_symbols'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_alerts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    op.create_index('idx_alerts_status', 'alerts', ['status'], unique=False)
    op.create_index('idx_alerts_symbol', 'alerts', ['symbol_id'], unique=False)
    op.create_index('idx_alerts_user', 'alerts', ['user_id'], unique=False)
    op.create_table('candles',
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol_id', sa.UUID(), nullable=False),
    sa.Column('timeframe_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('close_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=30, scale=8), nullable=True),
    sa.Column('is_closed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('close_time > open_time', name=op.f('ck_candles_close_after_open')),
    sa.CheckConstraint('high >= low', name=op.f('ck_candles_high_ge_low')),
    sa.ForeignKeyConstraint(['provider_id'], ['market_data_providers.id'], name=op.f('fk_candles_provider_id_market_data_providers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], name=op.f('fk_candles_symbol_id_symbols'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['timeframe_id'], ['timeframes.id'], name=op.f('fk_candles_timeframe_id_timeframes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('open_time', 'id', name=op.f('pk_candles')),
    sa.UniqueConstraint('symbol_id', 'timeframe_id', 'open_time', name='uq_candles_unique')
    )
    op.create_index('idx_candles_symbol_tf_time', 'candles', ['symbol_id', 'timeframe_id', 'open_time'], unique=False)
    op.create_table('indicator_values',
    sa.Column('calc_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('indicator_id', sa.UUID(), nullable=False),
    sa.Column('symbol_id', sa.UUID(), nullable=False),
    sa.Column('timeframe_id', sa.UUID(), nullable=False),
    sa.Column('values', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('params_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], name=op.f('fk_indicator_values_indicator_id_indicators'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], name=op.f('fk_indicator_values_symbol_id_symbols'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['timeframe_id'], ['timeframes.id'], name=op.f('fk_indicator_values_timeframe_id_timeframes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('calc_time', 'id', name=op.f('pk_indicator_values')),
    sa.UniqueConstraint('indicator_id', 'symbol_id', 'timeframe_id', 'calc_time', 'params_hash', name='uq_indicator_values_unique')
    )
    op.create_index('idx_indval_indicator', 'indicator_values', ['indicator_id'], unique=False)
    op.create_index('idx_indval_symbol_tf_time', 'indicator_values', ['symbol_id', 'timeframe_id', 'calc_time'], unique=False)
    op.create_table('order_books',
    sa.Column('snapshot_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('bids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('asks', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['market_data_providers.id'], name=op.f('fk_order_books_provider_id_market_data_providers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], name=op.f('fk_order_books_symbol_id_symbols'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('snapshot_time', 'id', name=op.f('pk_order_books'))
    )
    op.create_index('idx_orderbook_symbol_time', 'order_books', ['symbol_id', 'snapshot_time'], unique=False)
    op.create_table('orders',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('symbol_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=True),
    sa.Column('client_order_id', sa.String(length=64), nullable=True),
    sa.Column('side', postgresql.ENUM('buy', 'sell', name='order_side'), nullable=False),
    sa.Column('order_type', postgresql.ENUM('market', 'limit', 'stop', 'stop_limit', name='order_type'), nullable=False),
    sa.Column('time_in_force', postgresql.ENUM('gtc', 'ioc', 'fok', 'day', name='time_in_force'), server_default='gtc', nullable=False),
    sa.Column('quantity', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('filled_quantity', sa.Numeric(precision=30, scale=8), server_default='0', nullable=False),
    sa.Column('avg_fill_price', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'open', 'partially_filled', 'filled', 'cancelled', 'rejected', 'expired', name='order_status'), server_default='pending', nullable=False),
    sa.Column('reject_reason', sa.String(length=255), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('filled_quantity <= quantity', name=op.f('ck_orders_filled_le_quantity')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_orders_quantity_positive')),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_orders_strategy_id_strategies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], name=op.f('fk_orders_symbol_id_symbols'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_orders_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('client_order_id', name='uq_orders_client_order_id')
    )
    op.create_index('idx_orders_created', 'orders', ['created_at'], unique=False)
    op.create_index('idx_orders_status', 'orders', ['status'], unique=False)
    op.create_index('idx_orders_symbol', 'orders', ['symbol_id'], unique=False)
    op.create_index('idx_orders_user', 'orders', ['user_id'], unique=False)
    op.create_index('idx_orders_user_status', 'orders', ['user_id', 'status'], unique=False)
    op.create_table('positions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('symbol_id', sa.UUID(), nullable=False),
    sa.Column('side', postgresql.ENUM('long', 'short', name='position_side'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('avg_entry_price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=24, scale=8), server_default='0', nullable=False),
    sa.Column('status', postgresql.ENUM('open', 'closed', name='position_status'), server_default='open', nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_positions_quantity_non_negative')),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], name=op.f('fk_positions_symbol_id_symbols'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_positions_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_positions'))
    )
    op.create_index('idx_positions_symbol', 'positions', ['symbol_id'], unique=False)
    op.create_index('idx_positions_user', 'positions', ['user_id'], unique=False)
    op.create_index('idx_positions_user_status', 'positions', ['user_id', 'status'], unique=False)
    op.create_index('uq_positions_open_user_symbol', 'positions', ['user_id', 'symbol_id'], unique=True, postgresql_where=sa.text("status = 'open'"))
    op.create_table('price_history',
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('symbol_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('open', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=30, scale=8), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('high >= low', name=op.f('ck_price_history_high_ge_low')),
    sa.ForeignKeyConstraint(['provider_id'], ['market_data_providers.id'], name=op.f('fk_price_history_provider_id_market_data_providers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], name=op.f('fk_price_history_symbol_id_symbols'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('price_date', 'id', name=op.f('pk_price_history')),
    sa.UniqueConstraint('symbol_id', 'price_date', 'provider_id', name='uq_price_history_unique')
    )
    op.create_index('idx_pricehist_symbol_date', 'price_history', ['symbol_id', 'price_date'], unique=False)
    op.create_table('risk_rules',
    sa.Column('risk_profile_id', sa.UUID(), nullable=False),
    sa.Column('rule_type', postgresql.ENUM('position_limit', 'loss_limit', 'exposure_limit', 'leverage_limit', 'custom', name='risk_rule_type'), nullable=False),
    sa.Column('field', sa.String(length=60), nullable=False),
    sa.Column('operator', postgresql.ENUM('gt', 'gte', 'lt', 'lte', 'eq', name='risk_comparison_operator'), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('action', postgresql.ENUM('block', 'warn', 'notify', name='risk_action'), server_default='block', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['risk_profile_id'], ['risk_profiles.id'], name=op.f('fk_risk_rules_risk_profile_id_risk_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_rules'))
    )
    op.create_index('idx_riskrules_profile', 'risk_rules', ['risk_profile_id'], unique=False)
    op.create_table('strategy_parameters',
    sa.Column('strategy_version_id', sa.UUID(), nullable=False),
    sa.Column('param_key', sa.String(length=80), nullable=False),
    sa.Column('param_value', sa.String(length=255), nullable=True),
    sa.Column('value_type', postgresql.ENUM('int', 'float', 'string', 'bool', 'json', name='param_value_type'), server_default='string', nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], name=op.f('fk_strategy_parameters_strategy_version_id_strategy_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategy_parameters')),
    sa.UniqueConstraint('strategy_version_id', 'param_key', name='uq_strategy_parameters_key')
    )
    op.create_index('idx_stratparam_version', 'strategy_parameters', ['strategy_version_id'], unique=False)
    op.create_table('ticks',
    sa.Column('tick_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=30, scale=8), nullable=True),
    sa.Column('side', postgresql.ENUM('buy', 'sell', 'unknown', name='tick_side'), server_default='unknown', nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price > 0', name=op.f('ck_ticks_price_positive')),
    sa.ForeignKeyConstraint(['provider_id'], ['market_data_providers.id'], name=op.f('fk_ticks_provider_id_market_data_providers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], name=op.f('fk_ticks_symbol_id_symbols'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('tick_time', 'id', name=op.f('pk_ticks'))
    )
    op.create_index('idx_ticks_symbol_time', 'ticks', ['symbol_id', 'tick_time'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('watchlist_id', sa.UUID(), nullable=False),
    sa.Column('symbol_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], name=op.f('fk_watchlist_items_symbol_id_symbols'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], name=op.f('fk_watchlist_items_watchlist_id_watchlists'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watchlist_items')),
    sa.UniqueConstraint('watchlist_id', 'symbol_id', name='uq_watchlist_items_pair')
    )
    op.create_index('idx_wlitems_symbol', 'watchlist_items', ['symbol_id'], unique=False)
    op.create_index('idx_wlitems_watchlist', 'watchlist_items', ['watchlist_id'], unique=False)
    op.create_table('ai_signals',
    sa.Column('analysis_id', sa.UUID(), nullable=True),
    sa.Column('symbol_id', sa.UUID(), nullable=False),
    sa.Column('timeframe_id', sa.UUID(), nullable=True),
    sa.Column('signal_type', postgresql.ENUM('buy', 'sell', 'hold', 'close', name='signal_type'), nullable=False),
    sa.Column('strength', postgresql.ENUM('weak', 'moderate', 'strong', name='signal_strength'), server_default='moderate', nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('target_price', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', postgresql.ENUM('active', 'expired', 'hit_target', 'hit_stop', 'cancelled', name='signal_status'), server_default='active', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['ai_analysis.id'], name=op.f('fk_ai_signals_analysis_id_ai_analysis'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], name=op.f('fk_ai_signals_symbol_id_symbols'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['timeframe_id'], ['timeframes.id'], name=op.f('fk_ai_signals_timeframe_id_timeframes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_signals'))
    )
    op.create_index('idx_aisignals_created', 'ai_signals', ['created_at'], unique=False)
    op.create_index('idx_aisignals_status', 'ai_signals', ['status'], unique=False)
    op.create_index('idx_aisignals_symbol', 'ai_signals', ['symbol_id'], unique=False)
    op.create_table('alert_history',
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('triggered_value', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('notification_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_alert_history_alert_id_alerts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], name=op.f('fk_alert_history_notification_id_notifications'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_alert_history_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('triggered_at', 'id', name=op.f('pk_alert_history'))
    )
    op.create_index('idx_alerthist_alert', 'alert_history', ['alert_id'], unique=False)
    op.create_index('idx_alerthist_triggered', 'alert_history', ['triggered_at'], unique=False)
    op.create_index('idx_alerthist_user', 'alert_history', ['user_id'], unique=False)
    op.create_table('alert_rules',
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('indicator_id', sa.UUID(), nullable=True),
    sa.Column('field', sa.String(length=60), nullable=False),
    sa.Column('operator', postgresql.ENUM('gt', 'gte', 'lt', 'lte', 'eq', 'crosses_above', 'crosses_below', name='alert_operator'), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('logic_group', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('logic_operator', postgresql.ENUM('and', 'or', name='logic_operator'), server_default='and', nullable=False),
    sa.Column('sort_order', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_alert_rules_alert_id_alerts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], name=op.f('fk_alert_rules_indicator_id_indicators'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_rules'))
    )
    op.create_index('idx_alertrules_alert', 'alert_rules', ['alert_id'], unique=False)
    op.create_table('executions',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('symbol_id', sa.UUID(), nullable=False),
    sa.Column('exec_price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('exec_quantity', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('fee', sa.Numeric(precision=24, scale=8), server_default='0', nullable=False),
    sa.Column('fee_currency', sa.String(length=10), nullable=True),
    sa.Column('liquidity', postgresql.ENUM('maker', 'taker', 'unknown', name='liquidity'), server_default='unknown', nullable=False),
    sa.Column('external_exec_id', sa.String(length=80), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('exec_price > 0', name=op.f('ck_executions_exec_price_positive')),
    sa.CheckConstraint('exec_quantity > 0', name=op.f('ck_executions_exec_quantity_positive')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_executions_order_id_orders'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], name=op.f('fk_executions_symbol_id_symbols'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_executions')),
    sa.UniqueConstraint('external_exec_id', name='uq_executions_external_exec_id')
    )
    op.create_index('idx_exec_executed', 'executions', ['executed_at'], unique=False)
    op.create_index('idx_exec_order', 'executions', ['order_id'], unique=False)
    op.create_index('idx_exec_symbol', 'executions', ['symbol_id'], unique=False)
    op.create_table('order_history',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('previous_status', sa.String(length=30), nullable=True),
    sa.Column('new_status', sa.String(length=30), nullable=False),
    sa.Column('changed_quantity', sa.Numeric(precision=30, scale=8), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_history_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_history'))
    )
    op.create_index('idx_orderhist_created', 'order_history', ['created_at'], unique=False)
    op.create_index('idx_orderhist_order', 'order_history', ['order_id'], unique=False)
    op.create_table('position_history',
    sa.Column('position_id', sa.UUID(), nullable=False),
    sa.Column('event_type', postgresql.ENUM('open', 'increase', 'decrease', 'close', 'mark', name='position_event_type'), nullable=False),
    sa.Column('quantity_delta', sa.Numeric(precision=30, scale=8), nullable=True),
    sa.Column('price', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('realized_pnl_delta', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('snapshot_quantity', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name=op.f('fk_position_history_position_id_positions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_position_history'))
    )
    op.create_index('idx_poshist_created', 'position_history', ['created_at'], unique=False)
    op.create_index('idx_poshist_position', 'position_history', ['position_id'], unique=False)
    op.create_table('prompt_history',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('analysis_id', sa.UUID(), nullable=True),
    sa.Column('model_name', sa.String(length=80), nullable=True),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', postgresql.ENUM('success', 'error', 'timeout', name='prompt_status'), server_default='success', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['ai_analysis.id'], name=op.f('fk_prompt_history_analysis_id_ai_analysis'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_prompt_history_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_history'))
    )
    op.create_index('idx_prompthist_analysis', 'prompt_history', ['analysis_id'], unique=False)
    op.create_index('idx_prompthist_created', 'prompt_history', ['created_at'], unique=False)
    op.create_index('idx_prompthist_user', 'prompt_history', ['user_id'], unique=False)
    op.create_table('risk_logs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('risk_profile_id', sa.UUID(), nullable=True),
    sa.Column('risk_rule_id', sa.UUID(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('outcome', postgresql.ENUM('passed', 'warned', 'blocked', name='risk_outcome'), nullable=False),
    sa.Column('evaluated_value', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('message', sa.String(length=300), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_risk_logs_order_id_orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['risk_profile_id'], ['risk_profiles.id'], name=op.f('fk_risk_logs_risk_profile_id_risk_profiles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['risk_rule_id'], ['risk_rules.id'], name=op.f('fk_risk_logs_risk_rule_id_risk_rules'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_risk_logs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_logs'))
    )
    op.create_index('idx_risklogs_created', 'risk_logs', ['created_at'], unique=False)
    op.create_index('idx_risklogs_order', 'risk_logs', ['order_id'], unique=False)
    op.create_index('idx_risklogs_user', 'risk_logs', ['user_id'], unique=False)
    op.create_table('trades',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('symbol_id', sa.UUID(), nullable=False),
    sa.Column('position_id', sa.UUID(), nullable=True),
    sa.Column('strategy_id', sa.UUID(), nullable=True),
    sa.Column('side', postgresql.ENUM('long', 'short', name='position_side'), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('gross_pnl', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('net_pnl', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('total_fees', sa.Numeric(precision=24, scale=8), server_default='0', nullable=False),
    sa.Column('return_pct', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('status', postgresql.ENUM('open', 'closed', name='trade_status'), server_default='open', nullable=False),
    sa.Column('entry_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_trades_quantity_positive')),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name=op.f('fk_trades_position_id_positions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_trades_strategy_id_strategies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], name=op.f('fk_trades_symbol_id_symbols'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_trades_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trades'))
    )
    op.create_index('idx_trades_entry', 'trades', ['entry_at'], unique=False)
    op.create_index('idx_trades_status', 'trades', ['status'], unique=False)
    op.create_index('idx_trades_strategy', 'trades', ['strategy_id'], unique=False)
    op.create_index('idx_trades_symbol', 'trades', ['symbol_id'], unique=False)
    op.create_index('idx_trades_user', 'trades', ['user_id'], unique=False)
    op.create_table('confidence_scores',
    sa.Column('analysis_id', sa.UUID(), nullable=True),
    sa.Column('signal_id', sa.UUID(), nullable=True),
    sa.Column('factor', sa.String(length=80), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('weight', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('analysis_id IS NOT NULL OR signal_id IS NOT NULL', name=op.f('ck_confidence_scores_analysis_or_signal_present')),
    sa.CheckConstraint('score BETWEEN 0 AND 1', name=op.f('ck_confidence_scores_score_range')),
    sa.ForeignKeyConstraint(['analysis_id'], ['ai_analysis.id'], name=op.f('fk_confidence_scores_analysis_id_ai_analysis'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signal_id'], ['ai_signals.id'], name=op.f('fk_confidence_scores_signal_id_ai_signals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_confidence_scores'))
    )
    op.create_index('idx_confscore_analysis', 'confidence_scores', ['analysis_id'], unique=False)
    op.create_index('idx_confscore_signal', 'confidence_scores', ['signal_id'], unique=False)
    op.create_table('trade_journal',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('trade_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('setup_type', sa.String(length=80), nullable=True),
    sa.Column('emotion', postgresql.ENUM('calm', 'confident', 'fearful', 'greedy', 'frustrated', 'neutral', name='emotion'), server_default='neutral', nullable=True),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.Column('mistakes', sa.Text(), nullable=True),
    sa.Column('lessons', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name=op.f('ck_trade_journal_rating_range')),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], name=op.f('fk_trade_journal_trade_id_trades'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_trade_journal_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trade_journal')),
    sa.UniqueConstraint('trade_id', name='uq_trade_journal_trade_id')
    )
    op.create_index('idx_journal_trade', 'trade_journal', ['trade_id'], unique=False)
    op.create_index('idx_journal_user', 'trade_journal', ['user_id'], unique=False)
    op.create_table('trade_notes',
    sa.Column('journal_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note_type', postgresql.ENUM('observation', 'correction', 'idea', 'general', name='trade_note_type'), server_default='general', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['journal_id'], ['trade_journal.id'], name=op.f('fk_trade_notes_journal_id_trade_journal'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_trade_notes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trade_notes'))
    )
    op.create_index('idx_tradenotes_journal', 'trade_notes', ['journal_id'], unique=False)
    op.create_index('idx_tradenotes_user', 'trade_notes', ['user_id'], unique=False)
    op.create_table('trade_screenshots',
    sa.Column('journal_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=80), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('file_size >= 0', name=op.f('ck_trade_screenshots_file_size_non_negative')),
    sa.ForeignKeyConstraint(['journal_id'], ['trade_journal.id'], name=op.f('fk_trade_screenshots_journal_id_trade_journal'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_trade_screenshots_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trade_screenshots'))
    )
    op.create_index('idx_screenshots_journal', 'trade_screenshots', ['journal_id'], unique=False)

    # Circular FK: strategies.active_version_id -> strategy_versions.id.
    # Created after all tables exist to break the create-order cycle between
    # strategies and strategy_versions.
    op.create_foreign_key(
        op.f('fk_strategies_active_version_id_strategy_versions'),
        'strategies',
        'strategy_versions',
        ['active_version_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the circular FK first so tables can be dropped in any order.
    op.drop_constraint(
        op.f('fk_strategies_active_version_id_strategy_versions'),
        'strategies',
        type_='foreignkey',
    )
    op.drop_index('idx_screenshots_journal', table_name='trade_screenshots')
    op.drop_table('trade_screenshots')
    op.drop_index('idx_tradenotes_user', table_name='trade_notes')
    op.drop_index('idx_tradenotes_journal', table_name='trade_notes')
    op.drop_table('trade_notes')
    op.drop_index('idx_journal_user', table_name='trade_journal')
    op.drop_index('idx_journal_trade', table_name='trade_journal')
    op.drop_table('trade_journal')
    op.drop_index('idx_confscore_signal', table_name='confidence_scores')
    op.drop_index('idx_confscore_analysis', table_name='confidence_scores')
    op.drop_table('confidence_scores')
    op.drop_index('idx_trades_user', table_name='trades')
    op.drop_index('idx_trades_symbol', table_name='trades')
    op.drop_index('idx_trades_strategy', table_name='trades')
    op.drop_index('idx_trades_status', table_name='trades')
    op.drop_index('idx_trades_entry', table_name='trades')
    op.drop_table('trades')
    op.drop_index('idx_risklogs_user', table_name='risk_logs')
    op.drop_index('idx_risklogs_order', table_name='risk_logs')
    op.drop_index('idx_risklogs_created', table_name='risk_logs')
    op.drop_table('risk_logs')
    op.drop_index('idx_prompthist_user', table_name='prompt_history')
    op.drop_index('idx_prompthist_created', table_name='prompt_history')
    op.drop_index('idx_prompthist_analysis', table_name='prompt_history')
    op.drop_table('prompt_history')
    op.drop_index('idx_poshist_position', table_name='position_history')
    op.drop_index('idx_poshist_created', table_name='position_history')
    op.drop_table('position_history')
    op.drop_index('idx_orderhist_order', table_name='order_history')
    op.drop_index('idx_orderhist_created', table_name='order_history')
    op.drop_table('order_history')
    op.drop_index('idx_exec_symbol', table_name='executions')
    op.drop_index('idx_exec_order', table_name='executions')
    op.drop_index('idx_exec_executed', table_name='executions')
    op.drop_table('executions')
    op.drop_index('idx_alertrules_alert', table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index('idx_alerthist_user', table_name='alert_history')
    op.drop_index('idx_alerthist_triggered', table_name='alert_history')
    op.drop_index('idx_alerthist_alert', table_name='alert_history')
    op.drop_table('alert_history')
    op.drop_index('idx_aisignals_symbol', table_name='ai_signals')
    op.drop_index('idx_aisignals_status', table_name='ai_signals')
    op.drop_index('idx_aisignals_created', table_name='ai_signals')
    op.drop_table('ai_signals')
    op.drop_index('idx_wlitems_watchlist', table_name='watchlist_items')
    op.drop_index('idx_wlitems_symbol', table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index('idx_ticks_symbol_time', table_name='ticks')
    op.drop_table('ticks')
    op.drop_index('idx_stratparam_version', table_name='strategy_parameters')
    op.drop_table('strategy_parameters')
    op.drop_index('idx_riskrules_profile', table_name='risk_rules')
    op.drop_table('risk_rules')
    op.drop_index('idx_pricehist_symbol_date', table_name='price_history')
    op.drop_table('price_history')
    op.drop_index('uq_positions_open_user_symbol', table_name='positions', postgresql_where=sa.text("status = 'open'"))
    op.drop_index('idx_positions_user_status', table_name='positions')
    op.drop_index('idx_positions_user', table_name='positions')
    op.drop_index('idx_positions_symbol', table_name='positions')
    op.drop_table('positions')
    op.drop_index('idx_orders_user_status', table_name='orders')
    op.drop_index('idx_orders_user', table_name='orders')
    op.drop_index('idx_orders_symbol', table_name='orders')
    op.drop_index('idx_orders_status', table_name='orders')
    op.drop_index('idx_orders_created', table_name='orders')
    op.drop_table('orders')
    op.drop_index('idx_orderbook_symbol_time', table_name='order_books')
    op.drop_table('order_books')
    op.drop_index('idx_indval_symbol_tf_time', table_name='indicator_values')
    op.drop_index('idx_indval_indicator', table_name='indicator_values')
    op.drop_table('indicator_values')
    op.drop_index('idx_candles_symbol_tf_time', table_name='candles')
    op.drop_table('candles')
    op.drop_index('idx_alerts_user', table_name='alerts')
    op.drop_index('idx_alerts_symbol', table_name='alerts')
    op.drop_index('idx_alerts_status', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('idx_aianalysis_user', table_name='ai_analysis')
    op.drop_index('idx_aianalysis_type', table_name='ai_analysis')
    op.drop_index('idx_aianalysis_symbol', table_name='ai_analysis')
    op.drop_index('idx_aianalysis_created', table_name='ai_analysis')
    op.drop_table('ai_analysis')
    op.drop_index('idx_symbols_ticker', table_name='symbols')
    op.drop_index('idx_symbols_market', table_name='symbols')
    op.drop_index('idx_symbols_exchange', table_name='symbols')
    op.drop_index('idx_symbols_active', table_name='symbols')
    op.drop_table('symbols')
    op.drop_index('idx_stratver_strategy', table_name='strategy_versions')
    op.drop_table('strategy_versions')
    op.drop_index('idx_riskprof_user', table_name='risk_profiles')
    op.drop_index('idx_riskprof_portfolio', table_name='risk_profiles')
    op.drop_table('risk_profiles')
    op.drop_index('idx_refresh_user', table_name='refresh_tokens')
    op.drop_index('idx_refresh_token_hash', table_name='refresh_tokens')
    op.drop_index('idx_refresh_expires', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('idx_portfhist_portfolio_date', table_name='portfolio_history')
    op.drop_table('portfolio_history')
    op.drop_index('idx_watchlists_user', table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index('idx_user_roles_user', table_name='user_roles')
    op.drop_index('idx_user_roles_role', table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index('idx_strategies_user', table_name='strategies')
    op.drop_index('idx_strategies_status', table_name='strategies')
    op.drop_table('strategies')
    op.drop_index('idx_sessions_user', table_name='sessions')
    op.drop_index('idx_sessions_expires', table_name='sessions')
    op.drop_index('idx_sessions_active', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('idx_role_perm_role', table_name='role_permissions')
    op.drop_index('idx_role_perm_permission', table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index('idx_portfolio_user', table_name='portfolio')
    op.drop_table('portfolio')
    op.drop_index('idx_notif_user_read', table_name='notifications')
    op.drop_index('idx_notif_user', table_name='notifications')
    op.drop_index('idx_notif_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_indparam_indicator', table_name='indicator_parameters')
    op.drop_table('indicator_parameters')
    op.drop_index('idx_exchanges_market', table_name='exchanges')
    op.drop_index('idx_exchanges_code', table_name='exchanges')
    op.drop_table('exchanges')
    op.drop_index('idx_econevt_time', table_name='economic_events')
    op.drop_index('idx_econevt_impact', table_name='economic_events')
    op.drop_index('idx_econevt_calendar', table_name='economic_events')
    op.drop_table('economic_events')
    op.drop_index('idx_audit_user', table_name='audit_logs')
    op.drop_index('idx_audit_resource', table_name='audit_logs')
    op.drop_index('idx_audit_request', table_name='audit_logs')
    op.drop_index('idx_audit_created', table_name='audit_logs')
    op.drop_index('idx_audit_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('idx_appsettings_scope', table_name='application_settings')
    op.drop_index('idx_appsettings_key', table_name='application_settings')
    op.drop_table('application_settings')
    op.drop_index('idx_api_keys_user', table_name='api_keys')
    op.drop_index('idx_api_keys_prefix', table_name='api_keys')
    op.drop_index('idx_api_keys_hash', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index('idx_users_username', table_name='users')
    op.drop_index('idx_users_status', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_timeframes_seconds', table_name='timeframes')
    op.drop_index('idx_timeframes_code', table_name='timeframes')
    op.drop_table('timeframes')
    op.drop_index('idx_syslogs_service', table_name='system_logs')
    op.drop_index('idx_syslogs_request', table_name='system_logs')
    op.drop_index('idx_syslogs_level', table_name='system_logs')
    op.drop_index('idx_syslogs_created', table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index('idx_symcat_slug', table_name='symbol_categories')
    op.drop_index('idx_symcat_parent', table_name='symbol_categories')
    op.drop_table('symbol_categories')
    op.drop_index('idx_roles_name', table_name='roles')
    op.drop_table('roles')
    op.drop_index('idx_permissions_resource', table_name='permissions')
    op.drop_index('idx_permissions_code', table_name='permissions')
    op.drop_table('permissions')
    op.drop_index('idx_news_symbols', table_name='news', postgresql_using='gin')
    op.drop_index('idx_news_sentiment', table_name='news')
    op.drop_index('idx_news_published', table_name='news')
    op.drop_table('news')
    op.drop_index('idx_markets_type', table_name='markets')
    op.drop_index('idx_markets_code', table_name='markets')
    op.drop_table('markets')
    op.drop_index('idx_mdp_priority', table_name='market_data_providers')
    op.drop_index('idx_mdp_code', table_name='market_data_providers')
    op.drop_table('market_data_providers')
    op.drop_index('idx_indicators_code', table_name='indicators')
    op.drop_index('idx_indicators_category', table_name='indicators')
    op.drop_table('indicators')
    op.drop_index('idx_featflags_key', table_name='feature_flags')
    op.drop_index('idx_featflags_env', table_name='feature_flags')
    op.drop_table('feature_flags')
    op.drop_index('idx_econcal_region', table_name='economic_calendar')
    op.drop_table('economic_calendar')

    # Drop ENUM types explicitly: create_table auto-creates them on upgrade, but
    # drop_table does not remove them, which would break a subsequent upgrade.
    enum_types = (
        'alert_operator', 'alert_status', 'alert_type', 'analysis_status',
        'analysis_type', 'audit_status', 'emotion', 'event_impact',
        'feature_flag_environment', 'indicator_category',
        'indicator_param_value_type', 'liquidity', 'log_level', 'logic_operator',
        'market_type', 'notification_category', 'notification_channel',
        'notification_priority', 'order_side', 'order_status', 'order_type',
        'param_value_type', 'position_event_type', 'position_side',
        'position_status', 'prompt_status', 'provider_type', 'risk_action',
        'risk_comparison_operator', 'risk_level', 'risk_outcome',
        'risk_rule_type', 'sentiment', 'setting_scope', 'setting_value_type',
        'signal_status', 'signal_strength', 'signal_type', 'strategy_status',
        'strategy_type', 'tick_side', 'time_in_force', 'trade_note_type',
        'trade_status', 'user_status',
    )
    bind = op.get_bind()
    for enum_name in enum_types:
        postgresql.ENUM(name=enum_name).drop(bind, checkfirst=True)
    # ### end Alembic commands ###
